- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  notify: restart_apache

