- name: install dns server
  tags: dns,bind,ubuntu
  package:
    name:
      - "{{ dns_package }}"
      - "{{ dns_utils_package }}"
      - "{{ dns_docs_package }}"
    state: latest

- name: create log directory
  tags: dns,bind,ubuntu
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
    owner: bind
    group: bind
  with_items:
    - { dest: '/var/log/named', mode: '0750' }
  notify: restart_dns

- name: copy dns config files
  tags: dns,bind,ubuntu
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
    owner: root
    group: bind
    mode: 0644
  with_fileglob:
    - files/dns_forwarder/*
  notify: restart_bind

- name: add ufw bind rules (Ubuntu)
  tags: dns,bind,ubuntu
  ufw:
    direction: "in"
    from_ip: "192.168.1.0/24"
    name: "bind9"
    rule: "allow"
  when: ansible_distribution == "Ubuntu"
